package ar.com.jumperinformatica.gui.view.components;

import java.awt.Color;
import java.awt.Font;
import java.text.ParseException;

import javax.swing.JFormattedTextField;
import javax.swing.JPanel;
import javax.swing.text.MaskFormatter;

import ar.com.jumperinformatica.gui.enums.Recursos;
import ar.com.jumperinformatica.gui.principal.Facturacion;

public class CuerpoFacturaA extends JPanel{

	/**
	 * 
	 */
	private static final long serialVersionUID = -3450688508039178434L;
	private static final Font FUENTE_LABELS = Font.decode("Tahoma 11 11 12 Bold");
	private static final Color COLOR_FRENTE_LABELS = new Color(0,90,122);
	
	// Variables declaration - do not modify
    private javax.swing.JButton btnBuscarComitente;
    private javax.swing.JComboBox cboIva;
    private javax.swing.JLabel lblCondicionVenta;
    private javax.swing.JLabel lblCuit;
    private javax.swing.JLabel lblDomicilio;
    private javax.swing.JLabel lblIva;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblObra;
    private javax.swing.JLabel lblRemito;
    private JPanel pnlCuerpo;
    private javax.swing.JTextField tfCondicionVenta;
    private JFormattedTextField tfCuit;
    private javax.swing.JTextField tfDomicilio;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfObra;
    private javax.swing.JTextField tfRemito;
    // End of variables declaration
    
	    
	    /** Creates new form pnlCuerpoFacturaA 
	     * @throws ParseException */
	    public CuerpoFacturaA() throws ParseException {
	    	super();
	        initComponents();
	    }
	    
	    /** This method is called from within the constructor to
	     * initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is
	     * always regenerated by the Form Editor.
	     * @throws ParseException 
	     */
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">
	    private void initComponents() throws ParseException {

	        pnlCuerpo = new JPanel();
	        tfNombre = new javax.swing.JTextField();
	        cboIva = new javax.swing.JComboBox();
	        tfDomicilio = new javax.swing.JTextField();
	        tfCuit =new JFormattedTextField(new MaskFormatter("##'-########'-#"));
	        btnBuscarComitente = new javax.swing.JButton();
	        tfObra = new javax.swing.JTextField();
	        tfCondicionVenta = new javax.swing.JTextField();
	        lblNombre = new javax.swing.JLabel();
	        lblCuit = new javax.swing.JLabel();
	        lblDomicilio = new javax.swing.JLabel();
	        lblIva = new javax.swing.JLabel();
	        lblCondicionVenta = new javax.swing.JLabel();
	        tfRemito = new javax.swing.JTextField();
	        lblRemito = new javax.swing.JLabel();
	        lblObra = new javax.swing.JLabel();

	        pnlCuerpo.setBackground(Color.WHITE); // NOI18N
	        pnlCuerpo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new Font("Tahoma", 1, 11), new Color(0, 90, 122)));


	        btnBuscarComitente.setIcon(Facturacion.getInstance().getAdminRecursos().getIcon(Recursos.FACTURA_BUSCAR_COMITENTE));

	        lblNombre.setFont(FUENTE_LABELS); // NOI18N
	        lblNombre.setForeground(COLOR_FRENTE_LABELS); // NOI18N
	        lblNombre.setText("Señor (es)"); // NOI18N

	        lblCuit.setFont(FUENTE_LABELS); // NOI18N
	        lblCuit.setForeground(COLOR_FRENTE_LABELS); // NOI18N
	        lblCuit.setText("CUIT"); // NOI18N

	        lblDomicilio.setFont(FUENTE_LABELS); // NOI18N
	        lblDomicilio.setForeground(COLOR_FRENTE_LABELS); // NOI18N
	        lblDomicilio.setText("Domicilio"); // NOI18N

	        lblIva.setFont(FUENTE_LABELS); // NOI18N
	        lblIva.setForeground(COLOR_FRENTE_LABELS); // NOI18N
	        lblIva.setText("I.V.A"); // NOI18N

	        lblCondicionVenta.setFont(FUENTE_LABELS); // NOI18N
	        lblCondicionVenta.setForeground(COLOR_FRENTE_LABELS); // NOI18N
	        lblCondicionVenta.setText("Condic. Vta."); // NOI18N

	        lblRemito.setFont(FUENTE_LABELS); // NOI18N
	        lblRemito.setForeground(COLOR_FRENTE_LABELS); // NOI18N
	        lblRemito.setText("Remito Nº"); // NOI18N

	        lblObra.setFont(FUENTE_LABELS); // NOI18N
	        lblObra.setForeground(COLOR_FRENTE_LABELS); // NOI18N
	        lblObra.setText("Obra"); // NOI18N

	        javax.swing.GroupLayout pnlCuerpoLayout = new javax.swing.GroupLayout(pnlCuerpo);
	        pnlCuerpo.setLayout(pnlCuerpoLayout);
	        pnlCuerpoLayout.setHorizontalGroup(
	            pnlCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(pnlCuerpoLayout.createSequentialGroup()
	                .addContainerGap()
	                .addGroup(pnlCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	                    .addGroup(pnlCuerpoLayout.createSequentialGroup()
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                        .addComponent(lblNombre))
	                    .addComponent(lblDomicilio)
	                    .addComponent(lblIva)
	                    .addComponent(lblCondicionVenta))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addGroup(pnlCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(pnlCuerpoLayout.createSequentialGroup()
	                        .addGroup(pnlCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addGroup(pnlCuerpoLayout.createSequentialGroup()
	                                .addComponent(tfNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
	                                .addGap(26, 26, 26)
	                                .addComponent(lblCuit)
	                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                                .addComponent(tfCuit, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
	                            .addComponent(tfDomicilio, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE))
	                        .addGap(18, 18, 18)
	                        .addComponent(btnBuscarComitente, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
	                    .addGroup(pnlCuerpoLayout.createSequentialGroup()
	                        .addGroup(pnlCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	                            .addComponent(cboIva, javax.swing.GroupLayout.Alignment.LEADING, 0, 283, Short.MAX_VALUE)
	                            .addComponent(tfCondicionVenta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE))
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                        .addGroup(pnlCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	                            .addComponent(lblObra)
	                            .addComponent(lblRemito))
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                        .addGroup(pnlCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addGroup(pnlCuerpoLayout.createSequentialGroup()
	                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                .addComponent(tfRemito, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
	                            .addComponent(tfObra, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))))
	                .addGap(17, 17, 17))
	        );
	        pnlCuerpoLayout.setVerticalGroup(
	            pnlCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(pnlCuerpoLayout.createSequentialGroup()
	                .addContainerGap()
	                .addGroup(pnlCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(pnlCuerpoLayout.createSequentialGroup()
	                        .addGroup(pnlCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                            .addComponent(lblNombre)
	                            .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(lblCuit)
	                            .addComponent(tfCuit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                        .addGroup(pnlCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                            .addComponent(tfDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(lblDomicilio)))
	                    .addComponent(btnBuscarComitente, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addGap(9, 9, 9)
	                .addGroup(pnlCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(lblIva)
	                    .addComponent(cboIva, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(lblRemito)
	                    .addComponent(tfRemito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addGap(12, 12, 12)
	                .addGroup(pnlCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(tfCondicionVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(lblCondicionVenta)
	                    .addComponent(lblObra)
	                    .addComponent(tfObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addContainerGap(16, Short.MAX_VALUE))
	        );

	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
	        this.setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addComponent(pnlCuerpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addComponent(pnlCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	        );
	    }// </editor-fold>


		public javax.swing.JButton getBtnBuscarComitente() {
			return btnBuscarComitente;
		}

		public javax.swing.JComboBox getCboIva() {
			return cboIva;
		}

		public javax.swing.JTextField getTfCondicionVenta() {
			return tfCondicionVenta;
		}

		public JFormattedTextField getTfCuit() {
			return tfCuit;
		}

		public javax.swing.JTextField getTfDomicilio() {
			return tfDomicilio;
		}

		public javax.swing.JTextField getTfNombre() {
			return tfNombre;
		}

		public javax.swing.JTextField getTfObra() {
			return tfObra;
		}

		public javax.swing.JTextField getTfRemito() {
			return tfRemito;
		}

}